package com.spring.fullStack.marketDataService;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@DynamoDBTable(tableName = "Metal")
@Data
@Getter
@Setter
public class Metal {

	@DynamoDBHashKey(attributeName = "metalId")
	@DynamoDBAutoGeneratedKey
	private String metalId;
	private String metalIdentifier;
	private String metalName;
	private int metalRate;
	
	
	public Metal withId(String metalId) {

		setMetalId(metalId);
		return this;
	}
}
